generic-service:
  nameOverride: hmpps-education-employment-ui

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-education-employment-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    v1_2_enabled: true
    v0_47_enabled: false
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-education-employment-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-education-employment-ui:
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"
      PASSPHRASE: "PASSPHRASE"
      GOOGLE_TAG_MANAGER_CONTAINER_ID: "GOOGLE_TAG_MANAGER_CONTAINER_ID"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    hmpps-education-employment-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    sscl-blackpool: 31.121.5.27/32
    sscl-azure: 51.142.106.199/32
    sscl-york: 62.6.61.29/32
    sscl-newcastle: 62.172.79.105/32
    sscl-newport: 217.38.237.212/32
    groups:
      - internal
      - prisons
      - private_prisons
      - prisons-education

generic-prometheus-alerts:
  targetApplication: hmpps-education-employment-ui
