export default {
  NEXOFF: 'No excluding offences',
  VIOATP: 'Violence against the person',
  SEXOFNS: 'Sexual offences',
  ROBRY: 'Robbery',
  THFTOFNS: 'Theft offences',
  CRDMG: 'Criminal damage and arson',
  DRGOFNS: 'Drug offences',
  POSWEPNS: 'Possession of weapons',
  PUBOFNS: 'Public order offences',
  MISCR: 'Miscellaneous crimes against society',
  FRAUD: 'Fraud offences',
  SUMMOTR: 'Summary motoring',
  SUMNMOT: 'Summary non-motoring',
  OTH: 'Other',
}
