export default {
  ADVANCED_EDUCATION: 'Advanced school level qualification',
  CSCS: 'CSCS card',
  DRIVING_LICENSE: 'Full UK driving licence',
  FIRST_AID: 'First aid certificate',
  FOOD_HYGIENE: 'Food hygiene certificate',
  HEALTH_AND_SAFETY: 'Health and safety',
  HGV_LICENSE: 'HGV licence',
  HIGHER_EDUCATION: 'Higher education qualification',
  MACHINERY: 'Machinery tickets',
  MANUAL: 'Manual handling',
  TRADE: 'Trade course',
  SCHOOL_EDUCATION: 'School level qualification',
  OTHER: 'Other',
  NONE: 'None of these',
}
