export default {
  OUTDOOR: 'Animal care, farming and gardening',
  CONSTRUCTION: 'Construction and trade',
  DRIVING: 'Driving and transport',
  BEAUTY: 'Hair, beauty and wellbeing',
  HOSPITALITY: 'Hospitality and catering',
  TECHNICAL: 'IT and digital',
  MANUFACTURING: 'Manufacturing and technical',
  OFFICE: 'Office or desk-based',
  RETAIL: 'Retail and sales',
  SPORTS: 'Sport and fitness',
  WAREHOUSING: 'Warehousing and storage',
  EDUCATION_TRAINING: 'Training, support and education',
  WASTE_MANAGEMENT: 'Waste management',
  OTHER: 'Other',
}
