enum alreadyInPlaceValue {
  EDUCATION_OR_TRAINING = 'EDUCATION_OR_TRAINING',
  FAMILY_ISSUES = 'FAMILY_ISSUES',
  CARING_RESPONSIBILITIES = 'CARING_RESPONSIBILITIES',
  MENTAL_HEALTH_CONDITION = 'MENTAL_HEALTH_CONDITION',
  PHYSICAL_HEALTH_CONDITION = 'PHYSICAL_HEALTH_CONDITION',
  DRUGS_OR_ALCOHOL = 'DRUGS_OR_ALCOHOL',
  NONE = 'NONE',
}

export default alreadyInPlaceValue
