enum AlreadyInPlaceValue {
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  CV_AND_COVERING_LETTER = 'CV_AND_COVERING_LETTER',
  DISCLOSURE_LETTER = 'DISCLOSURE_LETTER',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  HOUSING = 'HOUSING',
  ID = 'ID',
  NONE = 'NONE',
}

export default AlreadyInPlaceValue
