enum ApplicationStatusValue {
  APPLICATION_MADE = 'APPLICATION_MADE',
  APPLICATION_UNSUCCESSFUL = 'APPLICATION_UNSUCCESSFUL',
  SELECTED_FOR_INTERVIEW = 'SELECTED_FOR_INTERVIEW',
  INTERVIEW_BOOKED = 'INTERVIEW_BOOKED',
  UNSUCCESSFUL_AT_INTERVIEW = 'UNSUCCESSFUL_AT_INTERVIEW',
  JOB_OFFER = 'JOB_OFFER',
}

export default ApplicationStatusValue
