enum EmployerSector {
  ADMIN_SUPPORT = 'ADMIN_SUPPORT',
  AGRICULTURE = 'AGRICULTURE',
  ARTS_ENTERTAINMENT = 'ARTS_ENTERTAINMENT',
  CONSTRUCTION = 'CONSTRUCTION',
  EDUCATION = 'EDUCATION',
  ENERGY = 'ENERGY',
  FINANCE = 'FINANCE',
  HEALTH_SOCIAL = 'HEALTH_SOCIAL',
  HOSPITALITY_CATERING = 'HOSPITALITY_CATERING',
  LOGISTICS = 'LOGISTICS',
  MANUFACTURING = 'MANUFACTURING',
  MINING = 'MINING',
  OTHER = 'OTHER',
  PROFESSIONALS_SCIENTISTS_TECHNICIANS = 'PROFESSIONALS_SCIENTISTS_TECHNICIANS',
  PROPERTY = 'PROPERTY',
  PUBLIC_ADMIN_DEFENCE = 'PUBLIC_ADMIN_DEFENCE',
  WASTE_MANAGEMENT = 'WASTE_MANAGEMENT',
  RETAIL = 'RETAIL',
  TECHNOLOGY = 'TECHNOLOGY',
}

export default EmployerSector
