enum JourneyTypeValue {
  JOB_DETAILS = 'JOB_DETAILS',
  MATCHED_JOBS = 'MATCHED_JOBS',
  MANAGED_APPLICATIONS = 'MANAGED_APPLICATIONS',
  VIEW_APPLICATION = 'VIEW_APPLICATION',
}

export default JourneyTypeValue
