enum ProfileStatus {
  NO_RIGHT_TO_WORK = 'NO_RIGHT_TO_WORK',
  SUPPORT_DECLINED = 'SUPPORT_DECLINED',
  SUPPORT_NEEDED = 'SUPPORT_NEEDED',
  READY_TO_WORK = 'READY_TO_WORK',
}

export default ProfileStatus
