enum SupportDeclinedReasonValue {
  ALREADY_HAS_WORK = 'ALREADY_HAS_WORK',
  LIMIT_THEIR_ABILITY = 'LIMIT_THEIR_ABILITY',
  FULL_TIME_CARER = 'FULL_TIME_CARER',
  HOUSING_NOT_IN_PLACE = 'HOUSING_NOT_IN_PLACE',
  LACKS_CONFIDENCE_OR_MOTIVATION = 'LACKS_CONFIDENCE_OR_MOTIVATION',
  HEALTH = 'HEALTH',
  NO_REASON = 'NO_REASON',
  RETIRED = 'RETIRED',
  RETURNING_TO_JOB = 'RETURNING_TO_JOB',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  OTHER = 'OTHER',
}

export default SupportDeclinedReasonValue
