enum SupportDeclinedReasonValue {
  LIMIT_THEIR_ABILITY = 'LIMIT_THEIR_ABILITY',
  CARING_RESPONSIBILITIES = 'CARING_RESPONSIBILITIES',
  LACKS_CONFIDENCE = 'LACKS_CONFIDENCE',
  LACKS_MOTIVATION = 'LACKS_MOTIVATION',
  HEALTH = 'HEALTH',
  NO_REASON = 'NO_REASON',
  RETIRED = 'RETIRED',
  RETURNING_TO_JOB = 'RETURNING_TO_JOB',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  OTHER = 'OTHER',
}

export default SupportDeclinedReasonValue
