enum whatNeedsToChangeValue {
  HOUSING_IN_PLACE = 'HOUSING_IN_PLACE',
  ID_IN_PLACE = 'ID_IN_PLACE',
  SUPPORT_TO_MANAGE_DEPENDENCY = 'SUPPORT_TO_MANAGE_DEPENDENCY',
  SUPPORT_TO_MANAGE_MENTAL_HEALTH = 'SUPPORT_TO_MANAGE_MENTAL_HEALTH',
  OTHER = 'OTHER',
}

export default whatNeedsToChangeValue
