enum WhatNeedsToChangeValue {
  HOUSING_ON_RELEASE = 'HOUSING_ON_RELEASE',
  ID_ON_RELEASE = 'ID_ON_RELEASE',
  DEPENDENCY_SUPPORT = 'DEPENDENCY_SUPPORT',
  MENTAL_HEALTH_SUPPORT = 'MENTAL_HEALTH_SUPPORT',
  OTHER = 'OTHER',
}

export default WhatNeedsToChangeValue
