import { stubFor } from './wiremock'

const getJobDetails = (jobId = '1') =>
  stubFor({
    request: {
      method: 'GET',
      url: `/candidate-matching/job/${jobId}`,
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        id: Number(jobId),
        employerName: 'Tesco',
        jobTitle: 'Warehouse handler',
        closingDate: '2025-05-16T11:15:04.915205',
        distance: 2.3,
        city: 'Leeds',
        postcode: 'LS23 5DH',
        typeOfWork: 'CLEANING_AND_MAINTENANCE',
        salaryFrom: 11.93,
        salaryTo: 15.9,
        salaryPeriod: 'PER_HOUR',
        offenceExclusions: ['SEXOFNS'],
        essentialCriteria:
          'Valid forklift operator certification or licence\nProven experience operating a forklift in a warehouse or similar setting\n\nStrong knowledge of forklift safety procedures and best practices\nMaths level 1\nEnglish level 1\nPhysical stamina to perform repetitive tasks and lift heavy objects\nExcellent communication skills and ability to work well in a team environment',
        jobDescription:
          "What's on offer:\n\n5 days over 7, 05:30 to 15:30\nPaid weekly\nImmediate starts available\nFull training provided\nYour duties will include:\n\nManoeuvring forklifts safely in busy industrial environments\nSafely stacking and unstacking large quantities of goods onto shelves or pallets\nMoving goods from storage areas to loading areas for transport\nUnloading deliveries and safely relocating the goods to their designated storage areas\nEnsuring forklift driving areas are free from spills or obstructions\nRegularly checking forklift equipment for faults or damages\nConsolidating partial pallets for incoming goods",
        workPattern: 'ANNUALISED_HOURS',
        additionalSalaryInformation: 'Immediate starts available\nFull training provided',
        desirableCriteria:
          'Manoeuvring forklifts safely in busy industrial environments\nSafely stacking and unstacking large quantities of goods onto shelves or pallets\nMoving goods from storage areas to loading areas for transport',
        hours: 'FULL_TIME',
        howToApply: 'Email: apply@testcompany.com, send CV and covering letter',
      },
    },
  })

const getMatchedJobsClosingSoon = () =>
  stubFor({
    request: {
      method: 'POST',
      url: '/candidate-matching/matched-jobs/closing-soon',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: [
        {
          id: 2,
          employerName: 'Amazon',
          jobTitle: 'Forklift operator',
          closingDate: '2022-05-01T17:00:00Z',
        },
      ],
    },
  })

const getJobOfInterestClosingSoon = (prisonerId = 'G6115VJ') =>
  stubFor({
    request: {
      method: 'GET',
      url: `/candidate-matching/jobs-of-interest/${prisonerId}/closing-soon`,
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: [
        {
          id: 1,
          employerName: 'Tesco',
          jobTitle: 'Warehouse handler',
          closingDate: '2022-05-02T17:00:00Z',
        },
      ],
    },
  })

const getArchivedJobs = () =>
  stubFor({
    request: {
      method: 'POST',
      url: '/candidate-matching/jobs/archived',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        content: [
          {
            id: 1,
            employerName: 'Amazon',
            jobTitle: 'Forklift operator',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 4.1,
            city: 'Leeds',
            postcode: 'LS23 3JF',
            typeOfWork: 'OUTDOOR',
            expressionOfInterest: false,
          },
          {
            id: 2,
            employerName: 'Tesco',
            jobTitle: 'Warehouse handler',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 2.3,
            city: 'Leeds',
            postcode: 'LS23 5DH',
            typeOfWork: 'CLEANING_AND_MAINTENANCE',
            expressionOfInterest: false,
          },
          {
            id: 4,
            employerName: 'Walmart',
            jobTitle: 'Cashier',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 6.5,
            city: 'Manchester',
            postcode: 'M12 6LP',
            typeOfWork: 'RETAIL',
            expressionOfInterest: false,
          },
          {
            id: 5,
            employerName: "McDonald's",
            jobTitle: 'Crew Member',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 3.2,
            city: 'Birmingham',
            postcode: 'B4 6UD',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: false,
          },
          {
            id: 6,
            employerName: 'Starbucks',
            jobTitle: 'Barista',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 1.8,
            city: 'London',
            postcode: 'SW1A 1AA',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: true,
          },
          {
            id: 8,
            employerName: 'Burger King',
            jobTitle: 'Kitchen Staff',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 5.7,
            city: 'Glasgow',
            postcode: 'G1 1AA',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: false,
          },
          {
            id: 9,
            employerName: 'Lidl',
            jobTitle: 'Store Associate',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 2.1,
            city: 'Edinburgh',
            postcode: 'EH1 2AB',
            typeOfWork: 'RETAIL',
            expressionOfInterest: false,
          },
          {
            id: 10,
            employerName: 'KFC',
            jobTitle: 'Shift Supervisor',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 4.9,
            city: 'Cardiff',
            postcode: 'CF10 1AB',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: false,
          },
          {
            id: 12,
            employerName: 'Pizza Hut',
            jobTitle: 'Delivery Driver',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 3.5,
            city: 'Bristol',
            postcode: 'BS1 1AB',
            typeOfWork: 'DRIVING',
            expressionOfInterest: false,
          },
          {
            id: 13,
            employerName: 'Primark',
            jobTitle: 'Retail Assistant',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 1.2,
            city: 'Manchester',
            postcode: 'M1 1AA',
            typeOfWork: 'RETAIL',
            expressionOfInterest: false,
          },
        ],
        pageable: {
          sort: { empty: true, sorted: false, unsorted: true },
          offset: 0,
          pageSize: 10,
          pageNumber: 0,
          paged: true,
          unpaged: false,
        },
        totalElements: 24,
        last: false,
        totalPages: 3,
        size: 10,
        number: 0,
        sort: { empty: true, sorted: false, unsorted: true },
        first: true,
        numberOfElements: 10,
        empty: false,
      },
    },
  })

const getOtherJobsOfInterest = () =>
  stubFor({
    request: {
      method: 'POST',
      url: '/candidate-matching/jobs/interested',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        content: [
          {
            id: 1,
            employerName: 'Amazon',
            jobTitle: 'Forklift operator',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 4.1,
            city: 'Leeds',
            postcode: 'LS23 3JF',
            typeOfWork: 'OUTDOOR',
          },
          {
            id: 2,
            employerName: 'Tesco',
            jobTitle: 'Warehouse handler',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 2.3,
            city: 'Leeds',
            postcode: 'LS23 5DH',
            typeOfWork: 'CLEANING_AND_MAINTENANCE',
          },
          {
            id: 4,
            employerName: 'Walmart',
            jobTitle: 'Cashier',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 6.5,
            city: 'Manchester',
            postcode: 'M12 6LP',
            typeOfWork: 'RETAIL',
          },
          {
            id: 5,
            employerName: "McDonald's",
            jobTitle: 'Crew Member',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 3.2,
            city: 'Birmingham',
            postcode: 'B4 6UD',
            typeOfWork: 'HOSPITALITY',
          },
          {
            id: 6,
            employerName: 'Starbucks',
            jobTitle: 'Barista',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 1.8,
            city: 'London',
            postcode: 'SW1A 1AA',
            typeOfWork: 'HOSPITALITY',
          },
          {
            id: 8,
            employerName: 'Burger King',
            jobTitle: 'Kitchen Staff',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 5.7,
            city: 'Glasgow',
            postcode: 'G1 1AA',
            typeOfWork: 'HOSPITALITY',
          },
          {
            id: 9,
            employerName: 'Lidl',
            jobTitle: 'Store Associate',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 2.1,
            city: 'Edinburgh',
            postcode: 'EH1 2AB',
            typeOfWork: 'RETAIL',
          },
          {
            id: 10,
            employerName: 'KFC',
            jobTitle: 'Shift Supervisor',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 4.9,
            city: 'Cardiff',
            postcode: 'CF10 1AB',
            typeOfWork: 'HOSPITALITY',
          },
          {
            id: 12,
            employerName: 'Pizza Hut',
            jobTitle: 'Delivery Driver',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 3.5,
            city: 'Bristol',
            postcode: 'BS1 1AB',
            typeOfWork: 'DRIVING',
          },
          {
            id: 13,
            employerName: 'Primark',
            jobTitle: 'Retail Assistant',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 1.2,
            city: 'Manchester',
            postcode: 'M1 1AA',
            typeOfWork: 'RETAIL',
          },
        ],
        pageable: {
          sort: { empty: true, sorted: false, unsorted: true },
          offset: 0,
          pageSize: 10,
          pageNumber: 0,
          paged: true,
          unpaged: false,
        },
        totalElements: 24,
        last: false,
        totalPages: 3,
        size: 10,
        number: 0,
        sort: { empty: true, sorted: false, unsorted: true },
        first: true,
        numberOfElements: 10,
        empty: false,
      },
    },
  })

const archiveJob = () =>
  stubFor({
    request: {
      method: 'POST',
      url: '/candidate-matching/jobs/archive',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {},
    },
  })

const jobSearch = () =>
  stubFor({
    request: {
      method: 'POST',
      url: '/candidate-matching/jobs/search',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        content: [
          {
            id: 1,
            employerName: 'Amazon',
            jobTitle: 'Forklift operator',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 4.1,
            city: 'Leeds',
            postcode: 'LS23 3JF',
            typeOfWork: 'OUTDOOR',
            expressionOfInterest: false,
          },
          {
            id: 2,
            employerName: 'Tesco',
            jobTitle: 'Warehouse handler',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 2.3,
            city: 'Leeds',
            postcode: 'LS23 5DH',
            typeOfWork: 'CLEANING_AND_MAINTENANCE',
            expressionOfInterest: false,
          },
          {
            id: 4,
            employerName: 'Walmart',
            jobTitle: 'Cashier',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 6.5,
            city: 'Manchester',
            postcode: 'M12 6LP',
            typeOfWork: 'RETAIL',
            expressionOfInterest: false,
          },
          {
            id: 5,
            employerName: "McDonald's",
            jobTitle: 'Crew Member',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 3.2,
            city: 'Birmingham',
            postcode: 'B4 6UD',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: false,
          },
          {
            id: 6,
            employerName: 'Starbucks',
            jobTitle: 'Barista',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 1.8,
            city: 'London',
            postcode: 'SW1A 1AA',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: true,
          },
          {
            id: 8,
            employerName: 'Burger King',
            jobTitle: 'Kitchen Staff',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 5.7,
            city: 'Glasgow',
            postcode: 'G1 1AA',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: false,
          },
          {
            id: 9,
            employerName: 'Lidl',
            jobTitle: 'Store Associate',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 2.1,
            city: 'Edinburgh',
            postcode: 'EH1 2AB',
            typeOfWork: 'RETAIL',
            expressionOfInterest: false,
          },
          {
            id: 10,
            employerName: 'KFC',
            jobTitle: 'Shift Supervisor',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 4.9,
            city: 'Cardiff',
            postcode: 'CF10 1AB',
            typeOfWork: 'HOSPITALITY',
            expressionOfInterest: false,
          },
          {
            id: 12,
            employerName: 'Pizza Hut',
            jobTitle: 'Delivery Driver',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 3.5,
            city: 'Bristol',
            postcode: 'BS1 1AB',
            typeOfWork: 'DRIVING',
            expressionOfInterest: false,
          },
          {
            id: 13,
            employerName: 'Primark',
            jobTitle: 'Retail Assistant',
            closingDate: '2024-06-03T14:21:24.852Z',
            distance: 1.2,
            city: 'Manchester',
            postcode: 'M1 1AA',
            typeOfWork: 'RETAIL',
            expressionOfInterest: false,
          },
        ],
        pageable: {
          sort: { empty: true, sorted: false, unsorted: true },
          offset: 0,
          pageSize: 10,
          pageNumber: 0,
          paged: true,
          unpaged: false,
        },
        totalElements: 24,
        last: false,
        totalPages: 3,
        size: 10,
        number: 0,
        sort: { empty: true, sorted: false, unsorted: true },
        first: true,
        numberOfElements: 10,
        empty: false,
      },
    },
  })

export default {
  getJobDetails,
  getMatchedJobsClosingSoon,
  getJobOfInterestClosingSoon,
  getArchivedJobs,
  getOtherJobsOfInterest,
  archiveJob,
  jobSearch,
}
