---
# Per environment values which override defaults in hmpps-education-employment-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: get-ready-for-work-preprod.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    ENVIRONMENT: preprod
    S3_REGION: eu-west-2
    INGRESS_URL: "https://get-ready-for-work-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HMPPS_PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMMUNITY_API_URL: "https://community-api-secure.preprod.delius.probation.hmpps.dsd.io"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api/"
    PRISONER_SEARCH_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
    ESWE_PROFILE_API_URL: "https://education-employment-api-preprod.hmpps.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"
    SYSTEM_PHASE: PREPROD
    WEEKS_BEFORE_RELEASE: 12

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
