---
# Per environment values which override defaults in hmpps-education-employment-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: education-employment-ui-dev.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    ENVIRONMENT: dev
    S3_REGION: eu-west-2
    INGRESS_URL: "https://education-employment-ui-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_PRISON_API_URL: "https://api-dev.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-dev.aks-dev-1.studio-hosting.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    COMMUNITY_API_URL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
    CURIOUS_API_URL: "https://testservices.sequation.net/sequation-virtual-campus2-api/"
    PRISONER_SEARCH_URL: "https://prisoner-offender-search-dev.prison.service.justice.gov.uk"
    ESWE_PROFILE_API_URL: "https://education-employment-api-dev.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: DEV
    WEEKS_BEFORE_RELEASE: 12

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

