---
# Per environment values which override defaults in hmpps-education-employment-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: get-ready-for-work-preprod.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    ENVIRONMENT: preprod
    ENVIRONMENT_NAME: 'PRE-PRODUCTION'
    S3_REGION: eu-west-2
    INGRESS_URL: "https://get-ready-for-work-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk/feedback-and-support"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HMPPS_PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-preprod.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    DELIUS_INTEGRATION_API_URL: "https://prison-education-and-delius-preprod.hmpps.service.justice.gov.uk"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api/"
    PRISONER_SEARCH_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    ESWE_PROFILE_API_URL: "https://education-employment-api-preprod.hmpps.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://allocation-manager-preprod.apps.live.cloud-platform.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    JOB_API_URL: "https://jobs-board-api-preprod.hmpps.service.justice.gov.uk"
    JOB_APPLICATION_API_URL: "https://support-preprod.hmpps.service.justice.gov.uk/feedback-and-support"
    MANAGE_USERS_API: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: PREPROD
    WEEKS_BEFORE_RELEASE: 12
    CANDIDATE_MATCHING_ENABLED: false

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
