---
# Per environment values which override defaults in hmpps-education-employment-ui/values.yaml

generic-service:

  ingress:
    host: get-ready-for-work.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    ENVIRONMENT: prod
    S3_REGION: eu-west-2
    INGRESS_URL: "https://get-ready-for-work.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support.hmpps.service.justice.gov.uk/feedback-and-support"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    HMPPS_PRISON_API_URL: "https://api.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user.aks-live-1.studio-hosting.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    DELIUS_INTEGRATION_API_URL: "https://prison-education-and-delius.hmpps.service.justice.gov.uk"
    CURIOUS_API_URL: "https://liveservices.sequation.net/sequation-virtual-campus2-api/"
    PRISONER_SEARCH_URL: "https://prisoner-offender-search.prison.service.justice.gov.uk"
    ESWE_PROFILE_API_URL: "https://education-employment-api.hmpps.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://allocation-manager.apps.live.cloud-platform.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: PROD
    WEEKS_BEFORE_RELEASE: 12

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
